--
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calisthenics-parks-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calisthenics-parks-server
  template:
    metadata:
      labels:
        app: calisthenics-parks-server
    spec:
      containers:
      - name: calisthenics-parks-server
        image: your-docker-registry/calisthenics-parks-server:latest
        ports:
        - containerPort: 3000
        env:
        - name: MAPBOX_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: mapbox-secret
              key: access-token
---
apiVersion: v1
kind: Service
metadata:
  name: calisthenics-parks-service
spec:
  selector:
    app: calisthenics-parks-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: calisthenics-parks-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: calisthenics-parks-server
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calisthenics-parks-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - calisthenics-parks.yourdomain.com
    secretName: calisthenics-parks-tls
  rules:
  - host: calisthenics-parks.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: calisthenics-parks-service
            port: 
              number: 80